# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
CarMenuItem.create(car_name:"Ferrari Enzo ", image_url:"https://www.linkpicture.com/q/ferrari-removebg-preview.png", price:"$6500", consumption: "3.5", speed: "450", car_description:"The Ferrari Enzo is a breathtakingly beautiful and powerful supercar, crafted with precision engineering and a passion for performance. With its sleek lines, advanced aerodynamics, and thunderous V12 engine, the Enzo is a true work of automotive art that embodies the spirit of Ferrari's racing heritage.")
CarMenuItem.create(car_name:"Ford Mustang GT1967", image_url:"https://www.linkpicture.com/q/ford-removebg-preview.png", price:"$4500", consumption: "4.5", speed: "400", car_description: "The Ford Mustang GT 1967 is an American classic that blends power and elegance. Its muscular body and powerful V8 engine deliver an unforgettable driving experience, while its timeless design continues to inspire a passion for performance and style.")
CarMenuItem.create(car_name:"Mclaren-765 ", image_url:"https://www.linkpicture.com/q/mclaren-removebg-preview.png", price:"$5500", consumption: "3.5", speed: "420", car_description: "The McLaren 765 is a powerful and luxurious supercar with sleek design and advanced technology. Its twin-turbo V8 engine delivers lightning-fast acceleration and an unforgettable driving experience, making it a true masterpiece of automotive engineering.")
CarMenuItem.create(car_name:"Audi R8 2017", image_url:"https://www.linkpicture.com/q/audi-removebg-preview.png", price:"$5000", consumption: "3.0", speed: "350", car_description:"The Audi R8 2017 is a powerful and luxurious supercar that seamlessly blends cutting-edge technology with refined design. With a powerful V10 engine, sleek aerodynamics, and a comfortable interior crafted with the finest materials, the R8 is a true masterpiece of automotive engineering.")