# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
CarMenuItem.create(car_name:"Porsche-911 ", image_url:"https://www.linkpicture.com/q/porsche-911-3d-model-f61c0f1418_2.jpg", price:"$5000", car_description:"The Porsche 911 (pronounced Nine Eleven or in German: Neunelfer) is a two-door 2+2 high performance rear-engined sports car introduced in September 1964 by Porsche AG of Stuttgart, Germany. It has a rear-mounted flat-six engine and originally a torsion bar suspension. The car has been continuously enhanced through the years but the basic concept has remained unchanged. The engines were air-cooled until the introduction of the 996 series in 1998.")
CarMenuItem.create(car_name:"Ferrari Enzo ", image_url:"https://www.linkpicture.com/q/enzo-ferrari-3d-model-obj-fbx-blend-1.jpg", price:"$6500", car_description:"The Enzo Ferrari (Type F140) is a mid-engine sports car manufactured by Italian automobile manufacturer Ferrari and named after the company's founder, Enzo Ferrari. It was developed in 2002 using Formula One technology, such as a carbon-fibre body, F1-style automated-shift manual transmission, and carbon fibre-reinforced silicon carbide (C/SiC) ceramic composite disc brakes, as well as technologies not allowed in F1, such as active aerodynamics. The Enzo Ferrari generates substantial amounts of downforce through its front underbody flaps, small adjustable rear spoiler and rear diffuser, which work in conjunction to produce 3,363 newtons (756 lbf) of downforce at 200 km/h (124 mph) and 7,602 newtons (1,709 lbf) of downforce at 299 km/h (186 mph), before decreasing to 5,738 N (1,290 lbf) at top speed.")
CarMenuItem.create(car_name:"Ford Mustang GT1967", image_url:"https://www.linkpicture.com/q/ford-mustan-gt1967-3d-model-low-poly-obj-fbx-blend.jpg", price:"$4500", car_description: "Front hood scoop / air intake. Air scoops on the upper and lower rear quarter panel, with the lower scoops actually functional on early 1967 CarMenuItem. Fibreglass bootlid with spoiler. Long/broad tail lights taken from the 1967 Ford Mercury Cougar (minus the chrome trim). A unique grill with two central 6 inch high beam spotlights under the fiberglass bonnet extension. Note, some GT 500's had lights placed further apart due to individual state regulations.")
CarMenuItem.create(car_name:"Mclaren-765 ", image_url:"https://www.linkpicture.com/q/mclaren-765-lt-3d-model-3d-model-obj-fbx-ma.jpg", price:"$5500", car_description: "Being based on the incredible 720S, the latest McLaren 765 Long Tail has everything in its favour. A flying start. And it delivers on every level. Radically lightened and lower, this powerful supercar uses innovative aerodynamics to create 25% more downforce than the 720S. And this is the most powerful LT yet, with a shattering 765PS.")
CarMenuItem.create(car_name:"Jaguar-MK2 1962", image_url:"https://www.linkpicture.com/q/jaguar-mk2-1962-3d-model-obj-3ds-fbx-stl-dwg-skp.jpg", price:"$6000", car_description:"The Jaguar Mark 2 is a mid-sized luxury sports saloon built from late 1959 to 1967 by Jaguar in Coventry, England. ")
CarMenuItem.create(car_name:"Audi R8 2017", image_url:"https://www.linkpicture.com/q/AUDI-R8-2017.jpg", price:"$5000", car_description:"The R8's 5.2-liter V-10 engine is offered in two strengths, both potent enough to knock the wind out of unsuspecting passengers while searing your eardrums with otherworldly exhalations. The base coupe and the Spyder convertible get 540 horsepower to play with, while the V10 Plus coupe is upgraded to 610 horsepower.")